import { useMemo, useState } from 'react';
import { ArrowLeft, ChevronDown, Clock3, Coffee, MapPin, Menu, MessageCircle, Minus, Plus, ShoppingBasket, Star, Utensils, X } from 'lucide-react';

const phone='966546346205';
const maps='https://maps.app.goo.gl/Wmmu9bS4PsKgUAcA6?g_st=ac';
const categories=[['sandwiches','ساندويتشات'],['pastries','فطاير زمان'],['beans','فول وعبده'],['drinks','مشروبات']];
const products=[
 {id:'zinger',name:'تورتيلا زنجر',cat:'sandwiches',price:9,desc:'دجاج زنجر مقرمش، خس طازج، طماطم وصوص مميز',img:'/banner-zinger.webp',opts:['شطة','كتشب','بهارات','جبن +1 ريال']},
 {id:'shawarma',name:'ساندويتش شاورما',cat:'sandwiches',price:7,desc:'شاورما دجاج طازجة بخلطة البوفيه',img:'/banner-zinger.webp',opts:['شطة','كتشب','بهارات','جبن +1 ريال']},
 {id:'sada',name:'فطيرة سادة',cat:'pastries',price:1,desc:'فطيرة ساخنة على الصاج، كما كانت زمان',img:'/banner-fatayir.webp'},
 {id:'egg',name:'فطيرة بيض',cat:'pastries',price:3,desc:'بيض طازج داخل فطيرة ذهبية',img:'/banner-fatayir.webp'},
 {id:'cheese',name:'فطيرة جبن',cat:'pastries',price:2,desc:'جبن ذائب مع عجينة طازة',img:'/banner-fatayir.webp'},
 {id:'shakshuka',name:'فطيرة شكشوكة',cat:'pastries',price:5,desc:'شكشوكة بيتية بنكهة شعبية',img:'/banner-fatayir.webp'},
 {id:'foul',name:'فول الطيب',cat:'beans',price:6,desc:'فول دافئ على الطريقة الشعبية',img:'/banner-qatta.webp',opts:['طحينة','زيت سمسم','زيتون']},
 {id:'adsa',name:'عبده',cat:'beans',price:6,desc:'طبق عبده مع اللمسة البيتية',img:'/banner-qatta.webp',opts:['طحينة','زيت سمسم','زيتون']},
 {id:'qatta',name:'قَطّة ورُب كومبو',cat:'beans',price:42,desc:'يكفي 5 أشخاص — جلسة ولمة بطعم زمان',img:'/banner-qatta.webp'},
 {id:'tea',name:'شاي كرك',cat:'drinks',price:2,desc:'كوب شاي على أصوله',img:'/banner-fatayir.webp'},
];
function wa(items:any[],type:string,pay:string,notes:string,address:string,subtotal:number,fee:number,total:number){const lines=items.map(i=>`• ${i.name} × ${i.qty} — ${i.price*i.qty} ر.س${i.opts?.length?` (${i.opts.join('، ')})`:''}`).join('\n');const extra=type==='توصيل'?`\nالعنوان: ${address||'غير مضاف'}`:'';const message=`طلب جديد من شعيبيات الطيب\n\n${lines}\n\nمجموع المنتجات: ${subtotal} ر.س\nرسوم التوصيل: ${fee} ر.س\nالإجمالي: ${total} ر.س\nالطلب: ${type}\nالدفع: ${pay}${extra}\nالملاحظات: ${notes||'لا توجد'}`;return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`}
function Logo(){return <div className="logo"><img src="/shaabiat-logo.webp" alt="شعيبيات الطيب"/><div><b>شعيبيات الطيب</b><small>حيث للطيب عادة .. وللطعم حكاية</small></div></div>}
export default function Home(){
 const [cat,setCat]=useState('sandwiches'); const [cart,setCart]=useState<any[]>([]); const [open,setOpen]=useState(false); const [mobile,setMobile]=useState(false); const [delivery,setDelivery]=useState('توصيل'); const [pay,setPay]=useState('كاش'); const [selected,setSelected]=useState<any>(null); const [toast,setToast]=useState(''); const [pulse,setPulse]=useState(false); const [notes,setNotes]=useState(''); const [address,setAddress]=useState(''); const shown=useMemo(()=>products.filter(p=>p.cat===cat),[cat]);
 const add=(p:any,opts:string[]=[])=>{setCart((c)=>{const old=c.find(i=>i.id===p.id&&JSON.stringify(i.opts)===JSON.stringify(opts));return old?c.map(i=>i===old?{...i,qty:i.qty+1}:i):[...c,{...p,opts,qty:1}]});setSelected(null);setPulse(true);setToast(`تمت إضافة ${p.name} للسلة`);window.setTimeout(()=>{setPulse(false);setToast('')},2200)};
 const count=cart.reduce((a,i)=>a+i.qty,0); const subtotal=cart.reduce((a,i)=>a+(i.price*i.qty),0); const fee=delivery==='توصيل'&&cart.length?5:0; const total=subtotal+fee;
 return <main dir="rtl" className="site">
  <div className="top"><span>مفتوحين ٢٤ ساعة</span><span>✦</span><span>الطيب عادة.. والطعم حكاية</span><a href={`tel:+${phone}`}>٠٥٤ ٦٣٤ ٦٢٠٥</a></div>
  <header><nav className="nav wrap"><a href="#home"><Logo/></a><div className={`links ${mobile?'show':''}`}><a href="#offers" onClick={()=>setMobile(false)}>العروض</a><a href="#menu" onClick={()=>setMobile(false)}>المنيو</a><a href="#story" onClick={()=>setMobile(false)}>حكاية الطيب</a><a href="#visit" onClick={()=>setMobile(false)}>موقعنا</a></div><div className="nav-actions"><a href={`https://wa.me/${phone}`} className="order">اطلب واتساب <MessageCircle size={16}/></a><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></nav></header>
  <button className={`cart-fab ${count?'has-items':''} ${pulse?'pulse':''}`} onClick={()=>setOpen(true)} aria-label="فتح السلة"><ShoppingBasket size={19}/><span>السلة</span><b>{count}</b><strong>{total} ر.س</strong></button><section id="home" className="hero wrap"><div className="hero-copy"><span className="eyebrow">بوفيه سعودي.. بطعم أيام زمان</span><h1>الطيب عادة،<br/><em>والطعم حكاية.</em></h1><p>من أول فطيرة على الصاج، إلى آخر رشّة شاي… أكلات شعبية تحكي لك عن البيت، واللمة، وريحة المطبخ القديم.</p><div className="actions"><a className="btn brown" href="#menu">شوف المنيو <ArrowLeft size={17}/></a><a className="btn outline" href={`https://wa.me/${phone}`}>اطلب الآن <MessageCircle size={17}/></a></div><div className="facts"><span><Clock3 size={16}/> مفتوحين ٢٤ ساعة</span><i/><span><Star size={16} fill="currentColor"/> طعم يستاهل</span></div></div><div className="hero-art"><img src="/banner-fatayir.webp" alt="فطاير زمان وشاي"/><div className="stamp">من القلب<br/><b>للبيت</b></div><div className="lantern">✦</div></div></section>
  <div className="marquee"><span>شاي على الجمر</span><b>✦</b><span>فطاير ساخنة</span><b>✦</b><span>فول وعبده</span><b>✦</b><span>لمة وطيب</span><b>✦</b><span>شاي على الجمر</span></div>
  <section id="offers" className="offers wrap section"><div className="head"><div><span className="kicker">عروض من زمان</span><h2>بنراتنا <em>تحكي</em></h2></div><span className="note">العرض كما هو في البنر</span></div><div className="banners"><a href="#menu"><img src="/banner-zinger.webp" alt="عرض تورتيلا زنجر 9 ريال"/><span>عرض تورتيلا زنجر <b>٩ ريال</b></span></a><a href="#menu"><img src="/banner-fatayir.webp" alt="فطاير زمان"/><span>فطاير زمان <b>من ريال</b></span></a><a href="#menu"><img src="/banner-qatta.webp" alt="قطّة ورُب كومبو 42 ريال"/><span>قَطّة ورُب كومبو <b>٤٢ ريال</b></span></a></div></section>
  <section id="menu" className="menu section"><div className="wrap"><div className="head"><div><span className="kicker">اطلبها مثل ما تحب</span><h2>منيو <em>الطيب</em></h2></div><span className="menu-hint">اضغط «أضف للسلة» وخلّ الباقي علينا</span></div><div className="tabs">{categories.map(([id,label])=><button className={cat===id?'active':''} key={id} onClick={()=>setCat(id)}>{label}</button>)}</div><div className="grid">{shown.map(p=><article className="card" key={p.id}><div className="pic"><img src={p.img} alt={p.name}/><span className="price">{p.price} <small>ر.س</small></span></div><div className="card-body"><h3>{p.name}</h3><p>{p.desc}</p><div className="card-foot"><b>{p.price} ر.س</b><button onClick={()=>p.opts?setSelected(p):add(p)}>أضف للسلة <Plus size={14}/></button></div></div></article>)}</div></div></section>
  <section id="story" className="story wrap section"><div className="story-art"><img src="/shaabiat-logo.webp" alt="شعار شعيبيات الطيب"/></div><div><span className="kicker">حكاية الطيب</span><h2>اللي يجي<br/><em>نستقبله بالطيب.</em></h2><p>شعيبيات الطيب بوفيه شعبي سعودي، نحب فيه البساطة اللي ترد الروح: فطاير على الصاج، فول دافي، شاي يعدّل المزاج، ووجبة تجمع أهل البيت والأصحاب.</p><div className="quote">“الطعم الأصيل ما يحتاج يتكلف”</div></div></section>
  <section id="visit" className="visit section"><div className="wrap visit-inner"><div><span className="kicker light">تعالنا بأي وقت</span><h2>البيت بيتك،<br/><em>والصاج حار.</em></h2><p>متاحين ٢٤ ساعة لخدمتك.</p><div className="visit-actions"><a href={maps}><MapPin size={17}/> افتح الموقع <ArrowLeft size={14}/></a><a href={`tel:+${phone}`}><Clock3 size={17}/> اتصل بنا <ArrowLeft size={14}/></a></div></div><div className="address"><div className="lantern-big">♨</div><h3>شعيبيات الطيب</h3><p>موقع المطعم على Google Maps<br/>اضغط للانتقال للموقع</p><a href={maps} target="_blank">الاتجاهات <ArrowLeft size={15}/></a></div></div></section>
  <footer><div className="wrap foot"><Logo/><div><p>حيث للطيب عادة .. وللطعم حكاية</p><span>© شعيبيات الطيب — بوفيه سعودي على مدار الساعة</span></div><a className="wa" href={`https://wa.me/${phone}`}><MessageCircle/> واتساب الطلبات</a></div></footer>
  {toast&&<div className="toast"><span className="toast-check">✓</span><div><b>تمت الإضافة</b><small>{toast.replace('تمت إضافة ','')}</small></div><button onClick={()=>setOpen(true)}>عرض السلة</button></div>}<a className="float" href={`https://wa.me/${phone}`}><MessageCircle size={24}/></a>
  {selected&&<div className="modal-bg" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><h3>{selected.name}</h3><p>اختر إضافاتك</p>{selected.opts.map((o:string)=><label key={o}><input type="checkbox" value={o} onChange={e=>{if(e.currentTarget.checked)setSelected({...selected,chosen:[...(selected.chosen||[]),o]});else setSelected({...selected,chosen:(selected.chosen||[]).filter((x:string)=>x!==o)})}}/> {o}</label>)}<button className="btn brown full" onClick={()=>add(selected,selected.chosen||[])}>أضف للسلة <Plus size={16}/></button></div></div>}
  {open&&<div className="modal-bg" onClick={()=>setOpen(false)}><div className="cart-modal" onClick={e=>e.stopPropagation()}><div className="cart-title"><h3>سلة الطيب</h3><button onClick={()=>setOpen(false)}><X/></button></div>{!cart.length?<p className="empty">السلة فاضية.. عبّها من المنيو!</p>:<>{cart.map(i=><div className="cart-row" key={i.id+JSON.stringify(i.opts)}><div><b>{i.name}</b><small>{i.opts?.join('، ')||'بدون إضافات'}</small><em>{i.price} ر.س × {i.qty} = <strong>{i.price*i.qty} ر.س</strong></em></div><div className="qty"><button onClick={()=>setCart(c=>c.map(x=>x===i?{...x,qty:Math.max(1,x.qty-1)}:x))}><Minus size={13}/></button>{i.qty}<button onClick={()=>setCart(c=>c.map(x=>x===i?{...x,qty:x.qty+1}:x))}><Plus size={13}/></button></div></div>)}<div className="choice"><b>نوع الطلب</b><div>{['توصيل','استلام'].map(x=><button className={delivery===x?'sel':''} onClick={()=>setDelivery(x)} key={x}>{x}</button>)}</div></div><div className="choice"><b>طريقة الدفع</b><div>{['كاش','شبكة'].map(x=><button className={pay===x?'sel':''} onClick={()=>setPay(x)} key={x}>{x}</button>)}</div></div>{delivery==='توصيل'&&<label className="field"><span>عنوان التوصيل <i>*</i></span><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="الحي، الشارع، رقم البيت أو اللوكيشن" /></label>}<label className="field"><span>ملاحظات الطلب <small>(اختياري)</small></span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="مثال: بدون بصل، زيادة صوص، الدور الثالث…" rows={2}/></label><div className="summary"><div><span>مجموع المنتجات <small>({count} قطع)</small></span><b>{subtotal} ر.س</b></div><div><span>رسوم التوصيل</span><b className={fee?'fee':''}>{fee?`+ ${fee} ر.س`:'مجاني'}</b></div></div><div className="cart-total"><span>الإجمالي النهائي</span><b>{total} ر.س</b></div><div className="progress"><span className="done">✓ الطلب</span><i/><span className={delivery?'done':''}>✓ {delivery}</span><i/><span className={pay?'done':''}>✓ {pay}</span></div><a className="btn brown full" href={wa(cart,delivery,pay,notes,address,subtotal,fee,total)} onClick={e=>{if(delivery==='توصيل'&&!address.trim()){e.preventDefault();setToast('أضف عنوان التوصيل قبل الإرسال');window.setTimeout(()=>setToast(''),2400)}}}>{delivery==='توصيل'?'إرسال طلب التوصيل':'إرسال طلب الاستلام'} عبر واتساب <MessageCircle size={16}/></a></>}</div></div>}
 </main>
}
